---
title: "Final project proposal"
author: "Xiangyu Liu"
date: '2017-11-26'
output:
  md_document:
    variant: markdown_github
  html_document: null
  word_document: default
---

### Name of the Project
Twitter data analysis

### Type of the Project
Data A2

###Brief description of the purpose
In this project, I first set up the Authorization with the twitter API so that I can begin searching and retrieving Tweets. I search Twitter for some tweets related to the 2017 Thanksgiving in New York. After cleaning the text with the tm package I create a wordcloud,bulid the network of terms, do the sentiment analysis and give a highly informative and beautiful visualization of what people are tweeting on the subject.

###Links to data sources / API etc. - Outline the technical steps / challenges you plan to address and include in your submission.

  - Extract tweets and followers from the Twitter API with R. (url:app.twitter.com, where to get the keys and access token)
  - search Twitter for some tweets related to the 2017 Black Friday in New York with the twitter packages.
  - clean the text with the tm package by removing punctuations, numbers, hyperlinks and stop words
  - build Term Document Matrix
  - create a datframe of top frequent terms
  - create a wordcloud and give a visualization of what people are tweeting on the subject
  - bulid a network of terms by the use of Rgraphviz package
  - analyse sentiment with the sentiment140 package
  - create a R package
  - publish a website for the complete R package


###Are there any significant hurdles that you have doubts about? Would not solving them render the project incomplete?
So far there is none.


